// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTz0kta7xEt_iZ4q_CYEWnznHKQUUWH6c',
    appId: '1:943326578058:web:d2594166b2a7438886b473',
    messagingSenderId: '943326578058',
    projectId: 'obichat-81eb1',
    authDomain: 'obichat-81eb1.firebaseapp.com',
    storageBucket: 'obichat-81eb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTJaMvbvah69iBE4vvmFkYTyNldLJ7g8',
    appId: '1:943326578058:android:83d443cd07cd5d0f86b473',
    messagingSenderId: '943326578058',
    projectId: 'obichat-81eb1',
    storageBucket: 'obichat-81eb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMNJiC301eeYvTfybDork11sRVuF5NHMg',
    appId: '1:943326578058:ios:8513a631d9938da786b473',
    messagingSenderId: '943326578058',
    projectId: 'obichat-81eb1',
    storageBucket: 'obichat-81eb1.appspot.com',
    iosClientId: '943326578058-ep7cgsdrll4g057qkbpfh7pr7frodrsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.obichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMNJiC301eeYvTfybDork11sRVuF5NHMg',
    appId: '1:943326578058:ios:8513a631d9938da786b473',
    messagingSenderId: '943326578058',
    projectId: 'obichat-81eb1',
    storageBucket: 'obichat-81eb1.appspot.com',
    iosClientId: '943326578058-ep7cgsdrll4g057qkbpfh7pr7frodrsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.obichat',
  );
}
